Repository Team-HMH/HMH-Android, pull requests merged in 2024-01, with the labels that each got.

#22 [feat/database] : Room Database 추가 작업
  app/build.gradle.kts
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/com/hmh/hamyeonham/plugin/AndroidRoomConventionPlugin.kt
  build-logic/convention/src/main/kotlin/com/hmh/hamyeonham/plugin/CommonConfigs.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/intent/ExtraExt.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/lifecycle/SingleLiveEvent.kt
  core/database/.gitignore
  core/database/build.gradle.kts
  core/database/consumer-rules.pro
  core/database/proguard-rules.pro
  core/database/schemas/sample.json
  core/database/src/main/AndroidManifest.xml
  core/database/src/main/java/com/hmh/hamyeonham/core/database/DatabaseModule.kt
  core/database/src/main/java/com/hmh/hamyeonham/core/database/HMHRoomDatabase.kt
  core/database/src/main/java/com/hmh/hamyeonham/core/database/dao/SampleDao.kt
  core/database/src/main/java/com/hmh/hamyeonham/core/database/model/Sample.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🐱의진, 💻feat

#24 [feat/home]: Add Home Module And Navigation Dependency
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  app/src/main/res/layout/activity_sample.xml
  app/src/main/res/values/themes.xml
  feature/main/.gitignore
  feature/main/build.gradle.kts
  feature/main/consumer-rules.pro
  feature/main/proguard-rules.pro
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/MainActivity.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/challenge/ChallengeFragment.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/HomeFragment.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/mypage/MyPageFragment.kt
  feature/main/src/main/res/layout/activity_main.xml
  feature/main/src/main/res/layout/fragment_challenge.xml
  feature/main/src/main/res/layout/fragment_home.xml
  feature/main/src/main/res/layout/fragment_my_page.xml
  feature/main/src/main/res/menu/bottom_nav_menu.xml
  feature/main/src/main/res/navigation/nav_graph.xml
  feature/main/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🐱의진, 💻feat

#28 [fix/gradle_plugin]: Fix Plugin Dependency
  build-logic/convention/src/main/kotlin/com/hmh/hamyeonham/plugin/CommonConfigs.kt
Labels: 💊fix, 🐱의진

#29 [feat/navigation_error]: Navigation 리소스 추가 작업
  core/common/build.gradle.kts
  feature/main/src/main/res/drawable/ic_android_black_24dp.xml
  feature/main/src/main/res/menu/bottom_nav_menu.xml
Labels: 🐱의진, 💻feat

#34 Update README.md
  README.md
Labels: 🐱의진, 📜docs

#35 Update README.md
  README.md
Labels: 🐱의진, 📜docs

#26 [feat/permission]: special permission 허용 요청 기능 구현
  feature/onboarding/src/androidTest/java/com/hmh/hamyeonham/feature/onboarding/ExampleInstrumentedTest.kt
  feature/onboarding/src/main/AndroidManifest.xml
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingAccessibilityService.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingActivity.kt
  feature/onboarding/src/main/res/layout/activity_on_boarding.xml
  feature/onboarding/src/main/res/layout/dialog_numberpicker_custom.xml
  feature/onboarding/src/main/res/values/strings.xml
  feature/onboarding/src/main/res/xml/accessibility_service_config.xml
  feature/onboarding/src/test/java/com/hmh/hamyeonham/feature/onboarding/ExampleUnitTest.kt
Labels: 💻feat, 🐰유리

#30 [feat/kakao_login]: 카카오 소셜 로그인, 닉네임 불러오기, 로그아웃 구현
  .github/workflows/develop_PR_builder.yml
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  build-logic/convention/src/main/kotlin/com/hmh/hamyeonham/plugin/CommonConfigs.kt
  feature/login/.gitignore
  feature/login/build.gradle.kts
  feature/login/consumer-rules.pro
  feature/login/proguard-rules.pro
  feature/login/src/main/AndroidManifest.xml
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginActivity.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginViewModel.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginViewPagerAdapter.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/UserInfoActivity.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/UserInfoViewModel.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/data/DummyImage.kt
  feature/login/src/main/res/drawable/login_kakao_large_wide.png
  feature/login/src/main/res/drawable/login_sample_rectagle_viewpager.xml
  feature/login/src/main/res/layout/activity_login.xml
  feature/login/src/main/res/layout/activity_user_info.xml
  feature/login/src/main/res/layout/item_login_view_pager.xml
  feature/login/src/main/res/values/strings.xml
  keystore/debug.keystore
  settings.gradle.kts
Labels: 💻feat, 🐰유리

#38 Update README.md
  README.md
Labels: 🐱의진, 📜docs

#41 Update README.md
  README.md
Labels: 💊fix, 🐰유리

#42 Update README.md
  README.md
Labels: 💊fix, 🐥지현

#33 [Feat/usagestatusmanager] : 이용시간 통계 뷰 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hmh/hamyeonham/HMHApplication.kt
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  app/src/main/res/layout/activity_sample.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  core/common/src/main/java/com/hmh/hamyeonham/common/context/ContextExt.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/time/TimeExt.kt
  core/common/src/main/res/drawable/ic_launcher_foreground.xml
  data/usagestats/.gitignore
  data/usagestats/build.gradle.kts
  data/usagestats/consumer-rules.pro
  data/usagestats/proguard-rules.pro
  data/usagestats/src/main/AndroidManifest.xml
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageGoalsDataSource.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageStatsDataSource.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageStatsDataSourceImpl.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageGoalsModule.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageStatsModule.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageGoalModel.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageStatModel.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageGoalsRepository.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageStatsRepository.kt
  domain/usagestats/.gitignore
  domain/usagestats/build.gradle.kts
  domain/usagestats/consumer-rules.pro
  domain/usagestats/proguard-rules.pro
  domain/usagestats/src/androidTest/java/com/hmh/hamyeonham/domain/usagestats/ExampleInstrumentedTest.kt
  domain/usagestats/src/main/AndroidManifest.xml
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageGoal.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageStat.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageStatAndGoal.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/UsageGoalsRepository.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/UsageStatsRepository.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/StaticsUseCase.kt
  domain/usagestats/src/test/java/com/hmh/hamyeonham/domain/usagestats/ExampleUnitTest.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/MainActivity.kt
  feature/statistics/.gitignore
  feature/statistics/build.gradle.kts
  feature/statistics/consumer-rules.pro
  feature/statistics/proguard-rules.pro
  feature/statistics/src/androidTest/java/com/hmh/hamyeonham/statistics/ExampleInstrumentedTest.kt
  feature/statistics/src/main/AndroidManifest.xml
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/StaticsActivity.kt
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/StaticsViewModel.kt
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/UsageStaticsAdapter.kt
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/UsageStaticsTotalViewHolder.kt
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/UsageStaticsViewHolder.kt
  feature/statistics/src/main/res/layout/activity_statics.xml
  feature/statistics/src/main/res/layout/item_usagestatic.xml
  feature/statistics/src/main/res/layout/item_usagestatic_total.xml
  feature/statistics/src/main/res/values/strings.xml
  feature/statistics/src/main/res/values/themes.xml
  settings.gradle.kts
Labels: 💻feat, 🐥지현

#43 Update README.md
  README.md
Labels: 🐱의진, 📜docs

#46 [release/0.0.1]: 릴리즈 0.0.1 기능 부족으로 issue close 요청
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/com/hmh/hamyeonham/HMHApplication.kt
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageStatsDataSourceImpl.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageGoalsModule.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageStatsModule.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageStatModel.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageGoalsRepository.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageStatsRepository.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/UsageStatsRepository.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/StaticsUseCase.kt
  feature/login/build.gradle.kts
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/MainActivity.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/challenge/ChallengeFragment.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/HomeFragment.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/mypage/MyPageFragment.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingAccessibilityService.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingActivity.kt
  feature/onboarding/src/main/res/layout/activity_on_boarding.xml
  gradle/libs.versions.toml
Labels: 🐱의진, 🔫 release

#49 [Feat/desing_system] : 디자인 시스템 모듈 추가
  app/build.gradle.kts
  core/design_system/.gitignore
  core/design_system/build.gradle.kts
  core/design_system/consumer-rules.pro
  core/design_system/proguard-rules.pro
  core/design_system/src/main/AndroidManifest.xml
  core/design_system/src/main/res/font/hmh_font.xml
  core/design_system/src/main/res/font/pretendard_medium.otf
  core/design_system/src/main/res/font/pretendard_regular.otf
  core/design_system/src/main/res/font/pretendard_semibold.otf
  core/design_system/src/main/res/values/colors.xml
  core/design_system/src/main/res/values/themes.xml
  core/design_system/src/main/res/values/typography.xml
  settings.gradle.kts
Labels: 💻feat, 🐥지현

#50 Update README.md
  README.md
Labels: 🐱의진, 📜docs

#55 [Feat/desing system]: 디자인시스템 컬러, 폰트 테마 적용
  core/design_system/src/main/res/values/attr.xml
  core/design_system/src/main/res/values/themes.xml
  core/design_system/src/main/res/values/typography.xml
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/GetUsageStatsListUseCase.kt
Labels: 💻feat, 🐥지현

#59 [fix/design system] : 디자인 시스템 세부사항 수정
  app/build.gradle.kts
  core/designsystem/.gitignore
  core/designsystem/build.gradle.kts
  core/designsystem/consumer-rules.pro
  core/designsystem/proguard-rules.pro
  core/designsystem/src/main/AndroidManifest.xml
  core/designsystem/src/main/res/drawable/ic_launcher_background.xml
  core/designsystem/src/main/res/drawable/ic_launcher_foreground.xml
  core/designsystem/src/main/res/font/hmh_font.xml
  core/designsystem/src/main/res/font/pretendard_medium.otf
  core/designsystem/src/main/res/font/pretendard_regular.otf
  core/designsystem/src/main/res/font/pretendard_semibold.otf
  core/designsystem/src/main/res/values/attrs.xml
  core/designsystem/src/main/res/values/colors.xml
  core/designsystem/src/main/res/values/themes.xml
  core/designsystem/src/main/res/values/typography.xml
  feature/onboarding/build.gradle.kts
  settings.gradle.kts
Labels: 🔥hotfix, 🐥지현

#60 [fix/design_system] : windowBackground설정
  core/designsystem/src/main/res/values/themes.xml
Labels: 🔥hotfix, 🐥지현

#62 [fix/bottom_nav_icon]: fix bottom navigation icon and color
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  core/designsystem/src/main/res/values/attrs.xml
  core/designsystem/src/main/res/values/themes.xml
  feature/main/build.gradle.kts
  feature/main/src/main/res/drawable/ic_android_black_24dp.xml
  feature/main/src/main/res/drawable/ic_bottomnav_challenge_24.xml
  feature/main/src/main/res/drawable/ic_bottomnav_home_24.xml
  feature/main/src/main/res/drawable/ic_bottomnav_mypage_24.xml
  feature/main/src/main/res/drawable/menu_selector_color.xml
  feature/main/src/main/res/layout/activity_main.xml
  feature/main/src/main/res/menu/bottom_nav_menu.xml
Labels: 💊fix, 🐱의진

#64 [fix_design]: 디자인 컬러 및 폰트 수정작업
  app/src/main/res/layout/activity_sample.xml
  core/designsystem/src/main/res/values/themes.xml
  core/designsystem/src/main/res/values/typography.xml
Labels: 💊fix, 🐱의진

#56 [feat/onboarding view]: 온보딩 UI 작업, 뷰 연결
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/activity/ActivityExt.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/view/NumberPickerExt.kt
  data/onboarding/.gitignore
  data/onboarding/build.gradle.kts
  data/onboarding/consumer-rules.pro
  data/onboarding/proguard-rules.pro
  data/onboarding/src/main/AndroidManifest.xml
  feature/onboarding/src/main/AndroidManifest.xml
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingAccessibilityService.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingActivity.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingDoneSingUpActivity.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingFragmentStateAdapter.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingRequestPermissionFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectAppFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectDataFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectScreenTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectUseTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnBoardingQuestion.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewModel/OnBoardingSelectDataViewModel.kt
  feature/onboarding/src/main/res/drawable/all_back_btn_medium.xml
  feature/onboarding/src/main/res/drawable/all_next_btn_able.xml
  feature/onboarding/src/main/res/drawable/all_next_btn_disable.xml
  feature/onboarding/src/main/res/drawable/all_next_icon_small.xml
  feature/onboarding/src/main/res/drawable/onboarding_data_list.xml
  feature/onboarding/src/main/res/drawable/onboarding_data_list_selected.xml
  feature/onboarding/src/main/res/drawable/onboarding_selector_btn_data.xml
  feature/onboarding/src/main/res/drawable/onboarding_selector_btn_next.xml
  feature/onboarding/src/main/res/layout/activity_on_boarding.xml
  feature/onboarding/src/main/res/layout/activity_on_boarding_done_sing_up.xml
  feature/onboarding/src/main/res/layout/dialog_numberpicker_custom.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_request_permission.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_app.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_data.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_screentime.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_use_time.xml
  feature/onboarding/src/main/res/values/strings.xml
  feature/onboarding/src/main/res/values/themes.xml
  settings.gradle.kts
Labels: 💻feat, 🐰유리

#79 [feat/mypage] : 마이페이지 ui 구현, 로직 구현
  app/build.gradle.kts
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  core/viewmodel/main/build.gradle.kts
  core/viewmodel/main/src/main/java/com/hmh/hamyeonham/core/MainViewModel.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageGoalsDataSource.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageStatsDataSourceImpl.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageGoalModel.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageStatModel.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageStatsRepository.kt
  data/userinfo/.gitignore
  data/userinfo/build.gradle.kts
  data/userinfo/consumer-rules.pro
  data/userinfo/proguard-rules.pro
  data/userinfo/src/main/AndroidManifest.xml
  data/userinfo/src/main/java/com/hmh/hamyeonham/userinfo/datasource/UserInfoDataSource.kt
  data/userinfo/src/main/java/com/hmh/hamyeonham/userinfo/di/UserInfoModule.kt
  data/userinfo/src/main/java/com/hmh/hamyeonham/userinfo/model/UserInfoModel.kt
  data/userinfo/src/main/java/com/hmh/hamyeonham/userinfo/repository/DefaultUserInfoRepository.kt
  domain/challenge/src/main/java/com/hmh/hamyeonham/challenge/model/ChallengeStatus.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageStat.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/GetUsageGoalsUseCase.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/GetUsageStatsListUseCase.kt
  domain/userinfo/.gitignore
  domain/userinfo/build.gradle.kts
  domain/userinfo/consumer-rules.pro
  domain/userinfo/proguard-rules.pro
  domain/userinfo/src/main/AndroidManifest.xml
  domain/userinfo/src/main/java/com/hmh/hamyeonham/userinfo/model/UserInfo.kt
  domain/userinfo/src/main/java/com/hmh/hamyeonham/userinfo/repository/UserInfoRepository.kt
  domain/userinfo/src/main/java/com/hmh/hamyeonham/userinfo/usecase/GetUserInfoUseCase.kt
  feature/challenge/build.gradle.kts
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeUsageGoalsAdapter.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/HomeFragment.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/mypage/MyPageFragment.kt
  feature/main/src/main/res/layout/fragment_home.xml
  feature/main/src/main/res/layout/fragment_my_page.xml
  feature/main/src/main/res/navigation/nav_graph.xml
  feature/mypage/.gitignore
  feature/mypage/build.gradle.kts
  feature/mypage/consumer-rules.pro
  feature/mypage/proguard-rules.pro
  feature/mypage/src/main/AndroidManifest.xml
  feature/mypage/src/main/java/com/hmh/hamyeonham/mypage/MyPageFragment.kt
  feature/mypage/src/main/res/drawable/ic_arrow_24.xml
  feature/mypage/src/main/res/drawable/ic_badge_white_24.xml
  feature/mypage/src/main/res/drawable/ic_journey_24.xml
  feature/mypage/src/main/res/drawable/ic_point_24.xml
  feature/mypage/src/main/res/drawable/ic_profile_50.xml
  feature/mypage/src/main/res/drawable/ic_store_24.xml
  feature/mypage/src/main/res/drawable/shape_background_radius7_gray6.xml
  feature/mypage/src/main/res/layout/fragment_my_page.xml
  feature/mypage/src/main/res/values/string.xml
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/StaticsActivity.kt
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/StaticsViewModel.kt
  settings.gradle.kts
Labels: 💻feat, 🐥지현

#63 [feat/usagestatusmanager]: 이용시간 통계 뷰 로직 수정, ui 구현
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  app/src/main/java/com/hmh/hamyeonham/navigation/DefaultNavigationProvider.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/context/ContextExt.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/intent/ExtraExt.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/navigation/NavigationProvider.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/time/TimeExt.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/view/Animator.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/view/Binding.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/view/ViewExt.kt
  core/viewmodel/main/src/main/java/com/hmh/hamyeonham/core/MainViewModel.kt
  core/viewmodel/main/src/main/res/drawable/ic_launcher_foreground.xml
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageGoalsDataSource.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageGoalsModule.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageStatsModule.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageStatsRepository.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/UsageStatsRepository.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/GetUsageStatsListUseCase.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginActivity.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/HomeFragment.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsAdapter.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsTotalViewHolder.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsViewHolder.kt
  feature/main/src/main/res/drawable/img_statics_blackhole.png
  feature/main/src/main/res/layout/fragment_home.xml
  feature/main/src/main/res/layout/item_usagestatic.xml
  feature/main/src/main/res/layout/item_usagestatic_total.xml
  feature/main/src/main/res/values/strings.xml
  feature/main/src/main/res/values/themes.xml
  feature/statistics/build.gradle.kts
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/StaticsActivity.kt
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/StaticsViewModel.kt
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/UsageStaticsTotalViewHolder.kt
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/UsageStaticsViewHolder.kt
  feature/statistics/src/main/res/layout/activity_statics.xml
  feature/statistics/src/main/res/layout/item_usagestatic.xml
  feature/statistics/src/main/res/layout/item_usagestatic_total.xml
  feature/statistics/src/main/res/values/strings.xml
  feature/statistics/src/main/res/values/themes.xml
Labels: 💻feat, 🔎refact, 🐥지현

#81 [feat/core_network]: core network 추가
  .github/workflows/develop_PR_builder.yml
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  build-logic/convention/src/main/kotlin/com/hmh/hamyeonham/plugin/CommonConfigs.kt
  core/network/.gitignore
  core/network/build.gradle.kts
  core/network/consumer-rules.pro
  core/network/proguard-rules.pro
  core/network/src/main/AndroidManifest.xml
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/api/RefreshApi.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/api/model/TokenResponse.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/authenticator/HMHAuthenticator.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/datastore/DefaultHMHNetworkPreference.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/datastore/HMHNetworkPreference.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/interceptor/AuthInterceptor.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/di/NetModule.kt
  settings.gradle.kts
Labels: 🐱의진, 💻feat

#77 [refact/kakao login]: 카카오 로그인 코드 리팩토링
  app/build.gradle.kts
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  app/src/main/java/com/hmh/hamyeonham/navigation/DefaultNavigationProvider.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/navigation/NavigationProvider.kt
  feature/login/build.gradle.kts
  feature/login/src/main/AndroidManifest.xml
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginActivity.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginViewModel.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginViewPagerAdapter.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/UserInfoActivity.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/UserInfoViewModel.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/data/DummyImage.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/model/LoginViewImageList.kt
  feature/login/src/main/res/drawable/login_kakao_btn_52.xml
  feature/login/src/main/res/drawable/login_kakao_icon_24.xml
  feature/login/src/main/res/drawable/login_kakao_large_wide.png
  feature/login/src/main/res/layout/activity_login.xml
  feature/login/src/main/res/layout/activity_user_info.xml
  feature/login/src/main/res/values/strings.xml
  feature/statistics/.gitignore
  feature/statistics/build.gradle.kts
  feature/statistics/consumer-rules.pro
  feature/statistics/proguard-rules.pro
  feature/statistics/src/main/AndroidManifest.xml
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/StaticsActivity.kt
  feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/StaticsViewModel.kt
  settings.gradle.kts
Labels: 🐰유리, 🔎refact

#82 [feat/base_response]: Base Response 추가
  core/network/src/main/java/com/hmh/hamyeonham/core/network/model/BaseResponse.kt
Labels: 🐱의진, 💻feat

#85 [feat/usagestatusmanager]: text appearance 수정
  feature/main/src/main/res/layout/item_usagestatic.xml
  feature/main/src/main/res/layout/item_usagestatic_total.xml
Labels: 💊fix, 🐥지현

#71 [feat/onboarding UI]: 온보딩 뷰 디자인 시스템 적용, 프로그레스바 적용
  core/designsystem/src/main/res/values/themes.xml
  feature/main/src/main/res/values/themes.xml
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingActivity.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingFragmentStateAdapter.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingRequestPermissionFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectDataFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectScreenTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectUseTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewModel/OnBoardingSelectDataViewModel.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewModel/OnBoardingViewModel.kt
  feature/onboarding/src/main/res/drawable/all_back_btn_medium.xml
  feature/onboarding/src/main/res/layout/activity_on_boarding.xml
  feature/onboarding/src/main/res/layout/activity_on_boarding_done_sing_up.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_request_permission.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_app.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_data.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_screentime.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_use_time.xml
  feature/onboarding/src/main/res/values/strings.xml
  feature/onboarding/src/main/res/values/themes.xml
Labels: 💻feat, 🐰유리

#94 [feat/social login api]: 소셜 로그인 작업
  app/build.gradle.kts
  core/database/consumer-rules.pro
  core/designsystem/consumer-rules.pro
  core/designsystem/proguard-rules.pro
  core/network/consumer-rules.pro
  core/network/proguard-rules.pro
  core/network/src/main/java/com/hmh/hamyeonham/core/network/di/LoginModule.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/login/LoginService.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/login/model/LoginRequest.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/login/model/LoginResponse.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/model/BaseResponse.kt
  core/viewmodel/consumer-rules.pro
  core/viewmodel/main/consumer-rules.pro
  core/viewmodel/main/proguard-rules.pro
  core/viewmodel/proguard-rules.pro
  data/login/.gitignore
  data/login/build.gradle.kts
  data/login/src/main/AndroidManifest.xml
  data/login/src/main/java/com/hmh/hamyeonham/login/DefaultLoginRepository.kt
  data/login/src/main/java/com/hmh/hamyeonham/login/di/LoginModule.kt
  data/login/src/main/java/com/hmh/hamyeonham/login/mapper/LoginMapper.kt
  data/onboarding/consumer-rules.pro
  data/onboarding/proguard-rules.pro
  data/usagestats/consumer-rules.pro
  data/usagestats/proguard-rules.pro
  data/userinfo/consumer-rules.pro
  data/userinfo/proguard-rules.pro
  domain/challenge/consumer-rules.pro
  domain/challenge/proguard-rules.pro
  domain/login/.gitignore
  domain/login/build.gradle.kts
  domain/login/consumer-rules.pro
  domain/login/proguard-rules.pro
  domain/login/src/main/AndroidManifest.xml
  domain/login/src/main/java/com/hmh/hamyeonham/login/model/Login.kt
  domain/login/src/main/java/com/hmh/hamyeonham/login/repository/LoginRepository.kt
  domain/usagestats/consumer-rules.pro
  domain/usagestats/proguard-rules.pro
  domain/userinfo/consumer-rules.pro
  domain/userinfo/proguard-rules.pro
  feature/challenge/consumer-rules.pro
  feature/challenge/proguard-rules.pro
  feature/login/build.gradle.kts
  feature/login/consumer-rules.pro
  feature/login/proguard-rules.pro
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginActivity.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginViewModel.kt
  feature/main/consumer-rules.pro
  feature/main/proguard-rules.pro
  feature/mypage/consumer-rules.pro
  feature/mypage/proguard-rules.pro
  feature/onboarding/consumer-rules.pro
  feature/onboarding/proguard-rules.pro
  settings.gradle.kts
Labels: 🐱의진, 💻feat

#89 [feat/challenge]: 앱 선택하기 기능 추가
  app/build.gradle.kts
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/di/NetModule.kt
  core/viewmodel/main/src/main/java/com/hmh/hamyeonham/core/MainViewModel.kt
  data/usagestats/build.gradle.kts
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageGoalsRemoteDataSource.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageGoalsModule.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageStatsModule.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageGoalsRepository.kt
  feature/challenge/src/main/AndroidManifest.xml
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeUsageGoalsAdapter.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appselection/AppselectionActivity.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appselection/AppselectionAdapter.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appselection/AppselectionViewHolder.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appselection/AppselectionViewModel.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/goals/ChallengeUsageGoalsAdapter.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/goals/ChallengeViewHolder.kt
  feature/challenge/src/main/res/drawable/appselection_btn_able.xml
  feature/challenge/src/main/res/drawable/appselection_btn_disable.xml
  feature/challenge/src/main/res/drawable/checkbox_able.xml
  feature/challenge/src/main/res/drawable/checkbox_disable.xml
  feature/challenge/src/main/res/drawable/drawable_cursor_color.xml
  feature/challenge/src/main/res/drawable/ic_arrowleft_white_24.xml
  feature/challenge/src/main/res/drawable/ic_default_checkbox_18.xml
  feature/challenge/src/main/res/drawable/ic_onchecked_18.xml
  feature/challenge/src/main/res/drawable/ic_plus_gray_24.xml
  feature/challenge/src/main/res/drawable/ic_search_24.xml
  feature/challenge/src/main/res/drawable/searchview_background.xml
  feature/challenge/src/main/res/drawable/selector_appselection_btn.xml
  feature/challenge/src/main/res/drawable/selector_checkbox.xml
  feature/challenge/src/main/res/layout/activity_appselection.xml
  feature/challenge/src/main/res/layout/fragment_challenge.xml
  feature/challenge/src/main/res/layout/item_app.xml
  feature/challenge/src/main/res/layout/item_goal_add.xml
  feature/challenge/src/main/res/layout/item_usage_goal.xml
  feature/challenge/src/main/res/values/strings.xml
  feature/challenge/src/main/res/values/themes.xml
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/HomeFragment.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsAdapter.kt
  feature/onboarding/src/main/res/drawable/onboarding_selector_btn_data.xml
Labels: 💻feat, 🐥지현

#72 [feat/onboarding permission] 온보딩 권한 허용 기능 구현
  app/build.gradle.kts
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  app/src/main/java/com/hmh/hamyeonham/navigation/DefaultNavigationProvider.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/navigation/NavigationProvider.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/primitive/StringExt.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/time/TimeExt.kt
  core/network/consumer-rules.pro
  core/network/proguard-rules.pro
  data/userinfo/consumer-rules.pro
  data/userinfo/proguard-rules.pro
  domain/userinfo/consumer-rules.pro
  domain/userinfo/proguard-rules.pro
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginActivity.kt
  feature/mypage/consumer-rules.pro
  feature/mypage/proguard-rules.pro
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingAccessibilityService.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingActivity.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingDoneSingUpActivity.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingRequestPermissionFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectAppFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectDataFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectScreenTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectUseTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnBoardingPermissionsState.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnboardingAnswer.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnboardingBtnInfo.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnboardingInformation.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnboardingPageInfo.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewModel/OnBoardingViewModel.kt~develop
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/OnBoardingRequestPermissionViewModel.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/OnBoardingSelectDataViewModel.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/OnBoardingViewModel.kt
  feature/onboarding/src/main/res/drawable/onboarding_select_data_disable.xml
  feature/onboarding/src/main/res/drawable/onboarding_selector_btn_next.xml
  feature/onboarding/src/main/res/layout/activity_on_boarding_done_sing_up.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_request_permission.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_app.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_data.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_screentime.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_use_time.xml
  feature/onboarding/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 💻feat, 🐰유리

#97 [feat/challenge]: 시간계산 로직 추가
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageGoal.kt
Labels: 💻feat, 🐥지현

#104 [fix/viewmodel_error]: ViewModel 에러 수정
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewModel/OnBoardingViewModel.kt~develop
Labels: 💊fix

#106 [feat/privacy_termofuse]: 이용약관, 개인정보보호 버튼 기능 추가
  build-logic/convention/src/main/kotlin/com/hmh/hamyeonham/plugin/CommonConfigs.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/interceptor/AuthInterceptor.kt
  feature/mypage/src/main/java/com/hmh/hamyeonham/mypage/MyPageFragment.kt
  feature/mypage/src/main/res/values/strings.xml
Labels: 💻feat, 🐥지현

#108 Update README.md
  README.md
Labels: 💊fix

#113 [feat/app_select]: 앱 추가 기능
  app/build.gradle.kts
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  core/designsystem/src/main/res/values/strings.xml
  core/designsystem/src/main/res/values/themes.xml
  core/viewmodel/main/src/main/java/com/hmh/hamyeonham/core/viewmodel/MainViewModel.kt
  data/device/.gitignore
  data/device/build.gradle.kts
  data/device/src/main/AndroidManifest.xml
  data/device/src/main/java/com/hmh/hamyeonham/data/device/di/DeviceBinder.kt
  data/device/src/main/java/com/hmh/hamyeonham/data/device/repository/DefaultDeviceRepository.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageGoalsRemoteDataSource.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageGoalsRepository.kt
  domain/challenge/src/main/java/com/hmh/hamyeonham/challenge/repository/DeviceRepository.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/UsageGoalsRepository.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/AddUsageGoalsUseCase.kt
  feature/challenge/src/main/AndroidManifest.xml
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeViewModel.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/AppAddActivity.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/AppAddViewModel.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/AppAddViewPagerAdapter.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/appselection/AppSelectionAdapter.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/appselection/AppSelectionFragment.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/appselection/AppSelectionViewHolder.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/appselection/AppSelectionViewModel.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/time/SetGoalTimeFragment.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appselection/AppselectionActivity.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appselection/AppselectionAdapter.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appselection/AppselectionViewHolder.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appselection/AppselectionViewModel.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/goals/ChallengeUsageGoalsAdapter.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/goals/ChallengeViewHolder.kt
  feature/challenge/src/main/res/drawable/selector_app_selection_btn.xml
  feature/challenge/src/main/res/layout/activity_app_add.xml
  feature/challenge/src/main/res/layout/activity_appselection.xml
  feature/challenge/src/main/res/layout/fragment_challenge.xml
  feature/challenge/src/main/res/layout/fragment_set_goal_time.xml
  feature/challenge/src/main/res/layout/frargment_app_selection.xml
  feature/challenge/src/main/res/values/strings.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_screentime.xml
  feature/onboarding/src/main/res/values/strings.xml
  feature/onboarding/src/main/res/values/themes.xml
  settings.gradle.kts
Labels: 🐱의진, 💻feat

#110 [feat/signup_api]: 회원가입 API, 자동 로그인 구현
  core/network/build.gradle.kts
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/api/model/TokenResponse.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/authenticator/HMHAuthenticator.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/datastore/DefaultHMHNetworkPreference.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/datastore/HMHNetworkPreference.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/service/SignUpService.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/signup/di/SignUpModule.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/signup/model/SignUpRequest.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/signup/model/SignUpResponse.kt
  data/login/src/main/java/com/hmh/hamyeonham/login/DefaultSignUpRepository.kt
  data/login/src/main/java/com/hmh/hamyeonham/login/di/SignUpModule.kt
  data/login/src/main/java/com/hmh/hamyeonham/login/mapper/SignUpMapper.kt
  domain/login/src/main/java/com/hmh/hamyeonham/login/model/SignRequestDomain.kt
  domain/login/src/main/java/com/hmh/hamyeonham/login/model/SignUpUser.kt
  domain/login/src/main/java/com/hmh/hamyeonham/login/repository/SignUpRepository.kt
  domain/onboarding/.gitignore
  domain/onboarding/build.gradle.kts
  domain/onboarding/consumer-rules.pro
  domain/onboarding/proguard-rules.pro
  domain/onboarding/src/main/AndroidManifest.xml
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginActivity.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginViewModel.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/model/LoginViewImageList.kt
  feature/login/src/main/res/values/strings.xml
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingActivity.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnboardingAnswer.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnboardingBtnInfo.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnboardingInformation.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/OnBoardingViewModel.kt
  settings.gradle.kts
Labels: 💻feat, 🐰유리

#102 [feat/main_activity_api]: 챌린지, 홈 이용시간 통계 불러오기 api 기초세팅
  app/build.gradle.kts
  core/network/src/main/java/com/hmh/hamyeonham/core/network/challenge/ChallengeService.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/challenge/model/ChallengeResponse.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/di/ChallengeModule.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/di/UsageGoalModule.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/login/LoginService.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/usagegoal/UsageGoalService.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/usagegoal/model/UsageGoalResponse.kt
  core/viewmodel/main/src/main/java/com/hmh/hamyeonham/core/viewmodel/MainViewModel.kt
  data/challenge/.gitignore
  data/challenge/build.gradle.kts
  data/challenge/consumer-rules.pro
  data/challenge/proguard-rules.pro
  data/challenge/src/main/AndroidManifest.xml
  data/challenge/src/main/java/com/hmh/hamyeonham/data/challenge/di/ChallengeModule.kt
  data/challenge/src/main/java/com/hmh/hamyeonham/data/challenge/mapper/ChallengeMapper.kt
  data/challenge/src/main/java/com/hmh/hamyeonham/data/challenge/mapper/StatusMapper.kt
  data/challenge/src/main/java/com/hmh/hamyeonham/data/challenge/repository/DefaultChallengeRepository.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageGoalsRemoteDataSource.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageStatsDataSource.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageStatsDataSourceImpl.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageStatusDataSource.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/UsageStatusDataSourceImpl.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageGoalsModule.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageStatsModule.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/mapper/UsageGoalMapper.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageGoalModel.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageStatsModel.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageGoalsRepository.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageStatusRepository.kt
  domain/challenge/src/main/java/com/hmh/hamyeonham/challenge/model/ChallengeStatus.kt
  domain/challenge/src/main/java/com/hmh/hamyeonham/challenge/repository/ChallengeRepository.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageStatus.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageStatusAndGoal.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/UsageGoalsRepository.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/UsageStatusRepository.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/GetUsageGoalsUseCase.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/GetUsageStatsListUseCase.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/calendar/ChallengeCalendarAdapter.kt
  feature/challenge/src/main/res/drawable/shape_background_radius8_blackground.xml
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsAdapter.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsTotalViewHolder.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsViewHolder.kt
  settings.gradle.kts
Labels: 💻feat, 🐥지현

#116 [feat/logout_api]: 로그아웃 API, 회원탈퇴 API 구현
  core/common/src/main/res/layout/dialog_common_two_button.xml
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/authenticator/HMHAuthenticator.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/di/AuthModule.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/di/LoginModule.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/login/AuthService.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/login/LoginService.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/mypage/MypageService.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/service/SignUpService.kt
  data/login/build.gradle.kts
  data/login/src/main/java/com/hmh/hamyeonham/login/DefaultAuthRepository.kt
  data/login/src/main/java/com/hmh/hamyeonham/login/DefaultLoginRepository.kt
  data/login/src/main/java/com/hmh/hamyeonham/login/DefaultSignUpRepository.kt
  data/login/src/main/java/com/hmh/hamyeonham/login/di/AuthModule.kt
  data/login/src/main/java/com/hmh/hamyeonham/login/di/LoginModule.kt
  domain/login/src/main/java/com/hmh/hamyeonham/login/repository/AuthRepository.kt
  domain/login/src/main/java/com/hmh/hamyeonham/login/repository/LoginRepository.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginViewModel.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/hmh/hamyeonham/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/hmh/hamyeonham/mypage/viewmodel/MyPageViewModel.kt
  feature/mypage/src/main/res/layout/fragment_my_page.xml
  feature/mypage/src/main/res/values/strings.xml
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/OnBoardingViewModel.kt
Labels: 💻feat, 🐰유리

#115 [feat/onboarding_button]: 온보딩 버튼 수정
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/api/RefreshService.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/di/ChallengeModule.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/di/UsageGoalModule.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/usagegoal/UsageGoalService.kt
  core/viewmodel/main/src/main/java/com/hmh/hamyeonham/core/viewmodel/MainViewModel.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageGoalsRepository.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeViewModel.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/AppAddViewModel.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/time/SetGoalTimeFragment.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginViewModel.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingActivity.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingRequestPermissionFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectAppFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectDataFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectScreenTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectUseTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnBoardingPermissionsState.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/OnBoardingRequestPermissionViewModel.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/OnBoardingViewModel.kt
Labels: 💊fix, 🐱의진

#125 [fix/logout_api_error]: logout, withdrawal header access token 넣기
  core/network/src/main/java/com/hmh/hamyeonham/core/network/login/AuthService.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/signup/model/SignUpResponse.kt
  data/login/src/main/java/com/hmh/hamyeonham/login/DefaultAuthRepository.kt
  data/login/src/main/java/com/hmh/hamyeonham/login/mapper/SignUpMapper.kt
  domain/login/src/main/java/com/hmh/hamyeonham/login/repository/AuthRepository.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginViewModel.kt
  feature/mypage/src/main/java/com/hmh/hamyeonham/mypage/viewmodel/MyPageViewModel.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingActivity.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/OnBoardingViewModel.kt
Labels: 💊fix, 🐰유리

#118 [fix/onboarding_design]: login, onboarding view image 삽입
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/hmh_splash_background.xml
  app/src/main/res/values/strings.xml
  core/designsystem/src/main/hmh_splash-playstore.png
  core/designsystem/src/main/res/drawable/hmh_app_logo.xml
  core/designsystem/src/main/res/drawable/hmh_app_logo__background.xml
  core/designsystem/src/main/res/drawable/hmh_splash_foreground.xml
  core/designsystem/src/main/res/mipmap-xxxhdpi/hmh_splash.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/hmh_splash_round.webp
  core/designsystem/src/main/res/values/hmh_splash_background.xml
  core/designsystem/src/main/res/values/themes.xml
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginActivity.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginViewPagerAdapter.kt
  feature/login/src/main/res/drawable/load_fail.png
  feature/login/src/main/res/drawable/onboarding_viewpager1.png
  feature/login/src/main/res/drawable/onboarding_viewpager2.png
  feature/login/src/main/res/drawable/onboarding_viewpager3.png
  feature/login/src/main/res/layout/activity_login.xml
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingActivity.kt
  feature/onboarding/src/main/res/drawable/success_signup.png
  feature/onboarding/src/main/res/layout/activity_on_boarding_done_sing_up.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_request_permission.xml
  feature/onboarding/src/main/res/values/strings.xml
Labels: 💊fix, 🐰유리

#132 Update README.md
  README.md
Labels: 📜docs, 🐥지현

#123 [feat/app_edit_api]: 앱 추가 삭제 API 연동
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/java/com/hmh/hamyeonham/core/network/challenge/AppCodeRequest.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/challenge/ChallengeService.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/challenge/model/AppsRequest.kt
  core/viewmodel/main/src/main/java/com/hmh/hamyeonham/core/viewmodel/MainViewModel.kt
  data/challenge/src/main/java/com/hmh/hamyeonham/data/challenge/mapper/AppMapper.kt
  data/challenge/src/main/java/com/hmh/hamyeonham/data/challenge/repository/DefaultChallengeRepository.kt
  domain/challenge/src/main/java/com/hmh/hamyeonham/challenge/model/Apps.kt
  domain/challenge/src/main/java/com/hmh/hamyeonham/challenge/repository/ChallengeRepository.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeViewModel.kt
Labels: 🐱의진, 💻feat

#131 [feat/onboarding_select_app]: onBoarding 특정 앱 추가 기능 구현
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/signup/model/SignUpRequest.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageStatsModule.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/mapper/UsageGoalMapper.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageGoalsRepository.kt
  domain/login/src/main/java/com/hmh/hamyeonham/login/model/SignRequestDomain.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/OnBoardingActivity.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/adapter/OnBoardingAppSelectionAdapter.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/adapter/OnBoardingAppSelectionViewHolder.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/adapter/OnBoardingFragmentStateAdapter.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingAppAddSelectionFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingRequestPermissionFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectAppFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectDataFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectScreenTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectUseTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnboardingAnswer.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/OnBoardingAppSelectionViewModel.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/OnBoardingSelectDataViewModel.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/OnBoardingViewModel.kt
  feature/onboarding/src/main/res/layout/activity_on_boarding.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_app_add_selection.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_app_selection.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_request_permission.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_app.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_data.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_screentime.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_select_use_time.xml
  feature/onboarding/src/main/res/layout/item_add_app.xml
  feature/onboarding/src/main/res/values/strings.xml
Labels: 💻feat, 🐰유리

#136 [feat/bottom_nav_anim]: 바텀 내비게이션 애니메이션 추가
  core/network/src/main/java/com/hmh/hamyeonham/core/network/challenge/ChallengeService.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageStatusAndGoal.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/AddUsageGoalsUseCase.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/HomeFragment.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsAdapter.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsTotalViewHolder.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsViewHolder.kt
  feature/main/src/main/res/layout/fragment_home.xml
  feature/main/src/main/res/layout/item_usagestatic_total.xml
  feature/main/src/main/res/raw/vd_blackhole1.mp4
  feature/main/src/main/res/raw/vd_blackhole2.mp4
  feature/main/src/main/res/raw/vd_blackhole3.mp4
  feature/main/src/main/res/raw/vd_blackhole4.mp4
  feature/main/src/main/res/raw/vd_blackhole5.mp4
  feature/main/src/main/res/values/strings.xml
Labels: 💻feat, 🐥지현

#142 [feat/home_detail]: 홈 디테일 추가
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageGoalsRepository.kt
  feature/main/src/main/res/layout/fragment_home.xml
Labels: 💻feat, 🐥지현

#145 [fix/onboarding_all]: 온보딩 전반적인 이슈 수정
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  domain/challenge/src/main/java/com/hmh/hamyeonham/challenge/usecase/GetInstalledAppUseCase.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/appselection/AppSelectionAdapter.kt
  feature/login/src/main/java/com/hmh/hamyeonham/feature/login/LoginActivity.kt
  feature/login/src/main/res/values/strings.xml
  feature/onboarding/src/main/AndroidManifest.xml
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/adapter/OnBoardingAppSelectionAdapter.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/adapter/OnBoardingAppSelectionViewHolder.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingAppAddSelectionFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectScreenTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectUseTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnBoardingPermissionsState.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnboardingBtnInfo.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnboardingInformation.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/model/OnboardingPageInfo.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/OnBoardingAppSelectionViewModel.kt
  feature/onboarding/src/main/res/layout/fragment_on_boarding_app_add_selection.xml
  feature/onboarding/src/main/res/layout/fragment_on_boarding_app_selection.xml
Labels: 💊fix, 🐰유리

#143 [feat/lock_api]: 잠금화면 미션 실패 API 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hmh/hamyeonham/navigation/DefaultNavigationProvider.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/activity/ActivityExt.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/context/ContextExt.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/fragment/FragmentExt.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/navigation/NavigationProvider.kt
  core/common/src/main/java/com/hmh/hamyeonham/common/time/TimeExt.kt
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/java/com/hmh/hamyeonham/core/network/di/UsageGoalModule.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/usagegoal/DailyChallengeService.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/usagegoal/UsageGoalService.kt
  core/service/.gitignore
  core/service/build.gradle.kts
  core/service/src/main/AndroidManifest.xml
  core/service/src/main/java/com/hmh/hamyeonham/core/service/LockAccessibilityService.kt
  core/viewmodel/main/src/main/java/com/hmh/hamyeonham/core/viewmodel/MainViewModel.kt
  data/challenge/src/main/java/com/hmh/hamyeonham/data/challenge/repository/DefaultChallengeRepository.kt
  data/device/src/main/java/com/hmh/hamyeonham/data/device/repository/DefaultDeviceRepository.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/datasource/remote/UsageGoalsRemoteDataSource.kt
  data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/repository/DefaultUsageGoalsRepository.kt
  domain/challenge/src/main/java/com/hmh/hamyeonham/challenge/repository/ChallengeRepository.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageStatusAndGoal.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
  feature/challenge/src/main/res/layout/fragment_challenge.xml
  feature/lock/src/main/AndroidManifest.xml
  feature/lock/src/main/java/com/hmh/hamyeonham/feature/lock/LockAccessibilityService.kt
  feature/lock/src/main/java/com/hmh/hamyeonham/feature/lock/LockActivity.kt
  feature/lock/src/main/res/values/strings.xml
  feature/lock/src/main/res/xml/accessibility_service_config.xml
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/MainActivity.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/HomeFragment.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsTotalViewHolder.kt
  feature/main/src/main/res/values/strings.xml
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingRequestPermissionFragment.kt
  settings.gradle.kts
Labels: 🐱의진, 💻feat

#144 [feat/challenge_detail]: 챌린지뷰 디테일 추가
  core/common/src/main/java/com/hmh/hamyeonham/common/time/TimeExt.kt
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/java/com/hmh/hamyeonham/core/domain/usagegoal/model/UsageGoal.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/challenge/model/ChallengeResponse.kt
  core/viewmodel/main/src/main/java/com/hmh/hamyeonham/core/viewmodel/MainViewModel.kt
  data/challenge/src/main/java/com/hmh/hamyeonham/data/challenge/mapper/ChallengeMapper.kt
  data/challenge/src/main/java/com/hmh/hamyeonham/data/challenge/mapper/StatusMapper.kt
  domain/challenge/src/main/java/com/hmh/hamyeonham/challenge/model/ChallengeStatus.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/model/UsageStatusAndGoal.kt
  domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/GetUsageStatsListUseCase.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/AppAddActivity.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/appselection/AppSelectionAdapter.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/appselection/AppSelectionFragment.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/appadd/appselection/AppSelectionViewHolder.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/calendar/ChallengeCalendarAdapter.kt
  feature/challenge/src/main/res/drawable/ic_challenge_none_38.xml
  feature/challenge/src/main/res/drawable/img_calendar_background.png
  feature/challenge/src/main/res/drawable/shape_background_radius8_blackground.xml
  feature/challenge/src/main/res/layout/activity_app_add.xml
  feature/challenge/src/main/res/layout/fragment_challenge.xml
  feature/challenge/src/main/res/layout/frargment_app_selection.xml
  feature/challenge/src/main/res/layout/item_challenge_status.xml
  feature/challenge/src/main/res/values/strings.xml
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/HomeFragment.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsAdapter.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsTotalViewHolder.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsViewHolder.kt
  feature/main/src/main/res/drawable/img_blackhole.png
  feature/main/src/main/res/layout/item_usagestatic_total.xml
  feature/main/src/main/res/values/strings.xml
  feature/mypage/src/main/java/com/hmh/hamyeonham/mypage/MyPageFragment.kt
  feature/mypage/src/main/res/values/strings.xml
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/OnBoardingSelectDataFragment.kt
Labels: 💻feat, 🐥지현

#146 [feat]: proguard 추가
  app/proguard-rules.pro
Labels: 🐱의진, 💻feat

#149 [feat/mypage_profile]: 마이페이지 이미지 수정
  feature/mypage/src/main/res/drawable/ic_profile_50.xml
  feature/mypage/src/main/res/drawable/img_profile.xml
  feature/mypage/src/main/res/layout/fragment_my_page.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: 💊fix, 🐰유리

#150 [feat/unlock]: 잠금 해제 기능 구현
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/datastore/DefaultHMHNetworkPreference.kt
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/datastore/HMHNetworkPreference.kt
  core/service/build.gradle.kts
  core/service/src/main/java/com/hmh/hamyeonham/core/service/LockAccessibilityService.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/MainActivity.kt
Labels: 🐱의진, 💻feat

#154 Update README.md
  README.md
Labels: 🐱의진, 📜docs
