Repository Team-HMH/HMH-Android, pull requests merged in 2025-01, with the labels that each got.

#281 [fix]: Onboarding 모듈 내 파일, 함수명에서 접두사(Onboarding)제거
  app/src/main/java/com/hmh/hamyeonham/SampleActivity.kt
  app/src/main/java/com/hmh/hamyeonham/navigation/DefaultNavigationProvider.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/adapter/AppSelectionAdapter.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/adapter/OnBoardingFragmentStateAdapter.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/AppAddSelectionFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/RequestPermissionFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/SelectAppFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/SelectDataFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/SelectScreenTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/fragment/SelectUseTimeFragment.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/AppSelectionViewModel.kt
  feature/onboarding/src/main/java/com/hmh/hamyeonham/feature/onboarding/viewmodel/SelectOnBoardingDataViewModel.kt
  feature/onboarding/src/main/res/layout/fragment_app_add_selection.xml
  feature/onboarding/src/main/res/layout/fragment_request_permission.xml
  feature/onboarding/src/main/res/layout/fragment_select_app.xml
  feature/onboarding/src/main/res/layout/fragment_select_data.xml
  feature/onboarding/src/main/res/layout/fragment_select_screentime.xml
  feature/onboarding/src/main/res/layout/fragment_select_use_time.xml
Labels: 💊fix, 🐰유리

#287 [Fix/reissue api exception]: 토큰 만료 시 Exception 발생 수정
  README.md
  core/network/src/main/java/com/hmh/hamyeonham/core/network/auth/authenticator/HMHAuthenticator.kt
Labels: 🔥hotfix

#288 [Feature/challenge frame drop]: 프레임 버벅임 수정
  app/src/main/AndroidManifest.xml
  core/common/src/main/java/com/hmh/hamyeonham/common/view/Binding.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeViewModel.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/calendar/ChallengeStatusViewHolder.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/goals/ChallengeUsageGoalsAdapter.kt
  feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/goals/ChallengeViewHolder.kt
  feature/challenge/src/main/res/layout/fragment_challenge.xml
  feature/challenge/src/main/res/layout/item_goal_add.xml
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/MainActivity.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/MainAdapter.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/MainScreen.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsAdapter.kt
  feature/main/src/main/java/com/hmh/hamyeonham/feature/main/home/UsageStaticsTotalViewHolder.kt
  feature/main/src/main/res/layout/activity_main.xml
Labels: 💊fix, 🐱의진
